# Generated by Django 2.2.1 on 2019-11-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=300)),
                ('body', models.CharField(max_length=3000)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
