# Generated by Django 2.2.1 on 2019-11-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApi', '0002_auto_20191116_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
